server:
  port: 0
spring:
  application:
    name: app-productos

  datasource:
    url: jdbc:postgresql://${DATASOURCE_DB_HOST:localhost}:${DATASOURCE_DB_PORT:5432}/${DATASOURCE_DB_NAME:productosDb}
    username: ${DATASOURCE_DB_USER:postgres}
    password: ${DATASOURCE_DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka